use_frameworks!

platform :ios, '9.0'

target 'ZoomingTransition_Example' do
  pod 'ZoomingTransition', :path => '../'

  target 'ZoomingTransition_Tests' do
    inherit! :search_paths

    
  end
end
